"""Оценка эффективности: критерии, факты и результаты

Revision ID: 20261008_01
Revises: 20261006_04
Create Date: 2026-10-08 00:00:00.000000

"""
from collections.abc import Sequence
from datetime import UTC, date, datetime
from uuid import uuid4

import sqlalchemy as sa

from alembic import op

revision: str = "20261008_01"
down_revision: str | Sequence[str] | None = "20261006_04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SECTION_11 = "Организация производственного контроля / ПК II уровня"
SECTION_12 = "Организация производственного контроля / ПК III уровня"
SECTION_21 = "Осуществление производственного контроля / ПК II уровня"
SECTION_22 = "Осуществление производственного контроля / ПК III уровня / внешние органы контроля"

SHARE_BAD_MAPPING = {"0": "более 30%", "1": "от 10% до 30%", "2": "до 10%", "np": "нет данных за период"}
SHARE_ON_TIME_MAPPING = {"0": "менее 70%", "1": "от 70% до менее 100%", "2": "100%", "np": "нет мероприятий с наступившими сроками"}
PLAN_DEADLINE_MAPPING = {
    "0": "не разработан или позднее 5 рабочих дней установленного срока",
    "1": "нарушение срока, но не более чем на 5 рабочих дней",
    "2": "разработан не позднее установленной даты",
    "np": "не применяется к периоду",
}

CRITERIA: list[dict] = [
    {
        "criterion_code": "1.1.1",
        "section_code": "1.1",
        "section_title": SECTION_11,
        "name": "Своевременность и полнота предоставления сведений об осуществлении АПК на II уровне",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "report_submission",
        "thresholds": {"working_days_limit": 10, "tolerance_working_days": 5},
        "score_mapping": {
            "0": "сведения не представлены или представлены позднее 5 рабочих дней установленного срока",
            "1": "представлены с нарушением сроков, но не более чем на 5 рабочих дней",
            "2": "представлены не позднее 10 рабочих дней месяца, следующего за отчетным кварталом",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "submitted_at", "kind": "date", "label": "Дата представления сведений (пусто — не представлены)"},
        ],
        "display_order": 1,
    },
    {
        "criterion_code": "1.1.2",
        "section_code": "1.1",
        "section_title": SECTION_11,
        "name": "Выполнение установленной периодичности проведения проверок АПК на II уровне объектов структурного подразделения",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "binary_choice",
        "thresholds": {"true_score": 2, "false_score": 0},
        "score_mapping": {
            "0": "периодичность нарушена",
            "1": "не используется",
            "2": "периодичность соблюдается",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "periodicity_kept", "kind": "bool", "label": "Периодичность проверок АПК II соблюдается (не реже 1 раза в 10 календарных дней)"},
        ],
        "display_order": 2,
    },
    {
        "criterion_code": "1.1.3",
        "section_code": "1.1",
        "section_title": SECTION_11,
        "name": "Наличие АОП 3-го уровня опасности",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "binary_choice",
        "thresholds": {"true_score": 0, "false_score": 2},
        "score_mapping": {
            "0": "наличие АОП 3-го уровня по вине работника или эксплуатирующей организации",
            "1": "не используется",
            "2": "отсутствие АОП 3-го уровня по вине работника или эксплуатирующей организации",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "negative_fact", "kind": "bool", "label": "АОП 3-го уровня по вине работника или эксплуатирующей организации было"},
        ],
        "display_order": 3,
    },
    {
        "criterion_code": "1.1.4",
        "section_code": "1.1",
        "section_title": SECTION_11,
        "name": "Разработка годового графика противоаварийных тренировок структурного подразделения",
        "subject_type": "department",
        "period_type": "year",
        "input_type": "manual",
        "formula_type": "plan_deadline",
        "thresholds": {"deadline_month": 11, "deadline_day": 30, "tolerance_working_days": 5},
        "score_mapping": PLAN_DEADLINE_MAPPING,
        "applicability_rule": {},
        "input_fields": [
            {"key": "developed_at", "kind": "date", "label": "Дата разработки графика (пусто — не разработан)"},
        ],
        "display_order": 4,
    },
    {
        "criterion_code": "1.1.5",
        "section_code": "1.1",
        "section_title": SECTION_11,
        "name": "Разработка графиков технического освидетельствования, диагностирования, испытаний, поверки и связанных планов",
        "subject_type": "department",
        "period_type": "year",
        "input_type": "manual",
        "formula_type": "plan_deadline",
        "thresholds": {"deadline_month": 12, "deadline_day": 28, "tolerance_working_days": 5},
        "score_mapping": PLAN_DEADLINE_MAPPING,
        "applicability_rule": {},
        "input_fields": [
            {"key": "developed_at", "kind": "date", "label": "Дата разработки графиков (пусто — не разработаны)"},
        ],
        "display_order": 5,
    },
    {
        "criterion_code": "1.2.1",
        "section_code": "1.2",
        "section_title": SECTION_12,
        "name": "Разработка планов мероприятий в области промышленной безопасности, включая работы по осуществлению производственного контроля и годовые графики плановых проверок ПК III уровня",
        "subject_type": "service",
        "period_type": "year",
        "input_type": "manual",
        "formula_type": "plan_deadline",
        "thresholds": {"deadline_month": 12, "deadline_day": 28, "tolerance_working_days": 5},
        "score_mapping": PLAN_DEADLINE_MAPPING,
        "applicability_rule": {},
        "input_fields": [
            {"key": "developed_at", "kind": "date", "label": "Дата разработки планов (пусто — не разработаны)"},
        ],
        "display_order": 6,
    },
    {
        "criterion_code": "1.2.2",
        "section_code": "1.2",
        "section_title": SECTION_12,
        "name": "Разработка графика противоаварийных тренировок Общества",
        "subject_type": "service",
        "period_type": "year",
        "input_type": "manual",
        "formula_type": "plan_deadline",
        "thresholds": {"deadline_month": 12, "deadline_day": 15, "tolerance_working_days": 5},
        "score_mapping": PLAN_DEADLINE_MAPPING,
        "applicability_rule": {},
        "input_fields": [
            {"key": "developed_at", "kind": "date", "label": "Дата разработки графика (пусто — не разработан)"},
        ],
        "display_order": 7,
    },
    {
        "criterion_code": "1.2.3",
        "section_code": "1.2",
        "section_title": SECTION_12,
        "name": "Наличие АОП 1-го, 2-го уровня опасности, несчастных случаев на ОПО",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "binary_choice",
        "thresholds": {"true_score": 0, "false_score": 2},
        "score_mapping": {
            "0": "наличие АОП 1-го/2-го уровня по вине работника или эксплуатирующей организации",
            "1": "не используется",
            "2": "отсутствие АОП 1-го/2-го уровня по вине работника или эксплуатирующей организации",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "negative_fact", "kind": "bool", "label": "АОП 1-го/2-го уровня или несчастные случаи на ОПО по вине работника или эксплуатирующей организации были"},
        ],
        "display_order": 8,
    },
    {
        "criterion_code": "1.2.4",
        "section_code": "1.2",
        "section_title": SECTION_12,
        "name": "Выполнение графика плановых проверок производственного контроля III уровня",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "schedule_deviation",
        "thresholds": {"tolerance_days": 5},
        "score_mapping": {
            "0": "нарушение сроков более чем на 5 календарных дней",
            "1": "нарушение сроков, но не более чем на 5 календарных дней",
            "2": "в установленные сроки",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "deviation_days", "kind": "number", "label": "Максимальное отклонение от графика, календарных дней (0 — в срок)"},
        ],
        "display_order": 9,
    },
    {
        "criterion_code": "2.1.1",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Полнота охвата объектов, оборудования, технических устройств структурного подразделения, подлежащих АПК на II уровне",
        "subject_type": "department",
        "period_type": "half_year",
        "input_type": "manual",
        "formula_type": "binary_choice",
        "thresholds": {"true_score": 2, "false_score": 0},
        "score_mapping": {
            "0": "не охвачены все объекты в каждом полугодии / менее двух раз в год",
            "1": "не используется",
            "2": "охвачены все объекты в каждом полугодии",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "coverage_complete", "kind": "bool", "label": "Все объекты подразделения охвачены проверками АПК II в каждом полугодии и не менее двух раз в год"},
        ],
        "display_order": 10,
    },
    {
        "criterion_code": "2.1.2",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Доля нарушений, выявленных при ПК III уровня и не выявленных при АПК II уровня",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "mixed",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["PC_III"], "metric": "total"},
        "input_fields": [
            {"key": "numerator", "kind": "number", "label": "Число нарушений ПК III, не выявленных при АПК II"},
        ],
        "display_order": 11,
    },
    {
        "criterion_code": "2.1.3",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Доля тяжелых нарушений (степень тяжести 8–9), выявленных в рамках ПК III уровня",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "auto",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["PC_III"], "severity_min": 8, "metric": "severity_share"},
        "input_fields": [],
        "display_order": 12,
    },
    {
        "criterion_code": "2.1.4",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Доля нарушений ПК III уровня, устраненных в срок",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "auto",
        "formula_type": "share_on_time",
        "thresholds": {"on_time_from": 70},
        "score_mapping": SHARE_ON_TIME_MAPPING,
        "applicability_rule": {"control_types": ["PC_III"], "metric": "on_time_share"},
        "input_fields": [],
        "display_order": 13,
    },
    {
        "criterion_code": "2.1.5",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Доля мероприятий по результатам технического расследования причин АОП 3-го уровня/потенциально опасных происшествий, выполненных в срок",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "share_on_time_manual",
        "thresholds": {"on_time_from": 70},
        "score_mapping": SHARE_ON_TIME_MAPPING,
        "applicability_rule": {},
        "input_fields": [
            {"key": "total", "kind": "number", "label": "Всего мероприятий по техническому расследованию АОП 3-го уровня / ПОП"},
            {"key": "done_on_time", "kind": "number", "label": "Выполнено в срок"},
        ],
        "display_order": 14,
    },
    {
        "criterion_code": "2.1.6",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Доля повторных нарушений, выявленных в рамках ПК III уровня",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "auto",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["PC_III"], "metric": "repeat_share"},
        "input_fields": [],
        "display_order": 15,
    },
    {
        "criterion_code": "2.1.7",
        "section_code": "2.1",
        "section_title": SECTION_21,
        "name": "Коэффициент результативности АПК РПО",
        "subject_type": "department",
        "period_type": "quarter",
        "input_type": "mixed",
        "formula_type": "rpo_ratio",
        "thresholds": {"equal_value": 0.1},
        "score_mapping": {
            "0": "менее 0,1",
            "1": "равно 0,1",
            "2": "более 0,1",
            "np": "наряды-допуски на РПО отсутствуют",
        },
        "applicability_rule": {"control_types": ["PC_II"], "violation_type_codes": ["1.1", "5.10"], "metric": "rpo_violations"},
        "input_fields": [
            {"key": "permits", "kind": "number", "label": "Количество выданных нарядов-допусков на РПО за период"},
        ],
        "display_order": 16,
    },
    {
        "criterion_code": "2.2.1",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля нарушений, выявленных органами государственного надзора, устраненных в срок",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "auto",
        "formula_type": "share_on_time",
        "thresholds": {"on_time_from": 70},
        "score_mapping": SHARE_ON_TIME_MAPPING,
        "applicability_rule": {"control_types": ["ROSTECHNADZOR"], "metric": "on_time_share"},
        "input_fields": [],
        "display_order": 17,
    },
    {
        "criterion_code": "2.2.2",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля повторных нарушений, выявленных органами государственного надзора",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "auto",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["ROSTECHNADZOR"], "metric": "repeat_share"},
        "input_fields": [],
        "display_order": 18,
    },
    {
        "criterion_code": "2.2.3",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля тяжелых нарушений (степень тяжести 8–9), выявленных органами государственного надзора",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "auto",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["ROSTECHNADZOR"], "severity_min": 8, "metric": "severity_share"},
        "input_fields": [],
        "display_order": 19,
    },
    {
        "criterion_code": "2.2.4",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля тяжелых нарушений (степень тяжести 8–9), выявленных ПАО «Газпром»/корпоративными органами контроля ПАО «Газпром»",
        "subject_type": "service",
        "period_type": "year",
        "input_type": "auto",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["GAZNADZOR"], "severity_min": 8, "metric": "severity_share"},
        "input_fields": [],
        "display_order": 20,
    },
    {
        "criterion_code": "2.2.5",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля нарушений, выявленных органами государственного надзора и не выявленных при ПК III уровня",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "mixed",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["ROSTECHNADZOR"], "metric": "total"},
        "input_fields": [
            {"key": "numerator", "kind": "number", "label": "Число нарушений органов государственного надзора, не выявленных при ПК III"},
        ],
        "display_order": 21,
    },
    {
        "criterion_code": "2.2.6",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля нарушений, выявленных ПАО «Газпром»/корпоративными органами контроля и не выявленных при ПК III уровня",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "mixed",
        "formula_type": "share_bad",
        "thresholds": {"bad_over": 30, "mild_from": 10},
        "score_mapping": SHARE_BAD_MAPPING,
        "applicability_rule": {"control_types": ["GAZNADZOR"], "metric": "total"},
        "input_fields": [
            {"key": "numerator", "kind": "number", "label": "Число нарушений ПАО «Газпром»/корпоративных органов контроля, не выявленных при ПК III"},
        ],
        "display_order": 22,
    },
    {
        "criterion_code": "2.2.7",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Доля мероприятий по результатам технического расследования причин АОП 1-го, 2-го уровня, выполненных в срок",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "share_on_time_manual",
        "thresholds": {"on_time_from": 70},
        "score_mapping": SHARE_ON_TIME_MAPPING,
        "applicability_rule": {},
        "input_fields": [
            {"key": "total", "kind": "number", "label": "Всего мероприятий по техническому расследованию АОП 1-го/2-го уровня"},
            {"key": "done_on_time", "kind": "number", "label": "Выполнено в срок"},
        ],
        "display_order": 23,
    },
    {
        "criterion_code": "2.2.8",
        "section_code": "2.2",
        "section_title": SECTION_22,
        "name": "Проведение СППБиБДД целевых проверок РПО",
        "subject_type": "service",
        "period_type": "quarter",
        "input_type": "manual",
        "formula_type": "check_count",
        "thresholds": {"many_from": 2},
        "score_mapping": {
            "0": "не проведено",
            "1": "один раз в квартал",
            "2": "более одного раза в квартал",
            "np": "не применяется к объекту или периоду оценки",
        },
        "applicability_rule": {},
        "input_fields": [
            {"key": "checks_count", "kind": "number", "label": "Число целевых проверок РПО за квартал"},
        ],
        "display_order": 24,
    },
]


def upgrade() -> None:
    now = datetime.now(UTC)
    op.create_table(
        "assessment_criteria",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criterion_code", sa.String(16), nullable=False),
        sa.Column("section_code", sa.String(16), nullable=False),
        sa.Column("section_title", sa.String(255), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("subject_type", sa.String(16), nullable=False),
        sa.Column("period_type", sa.String(16), nullable=False),
        sa.Column("input_type", sa.String(16), nullable=False),
        sa.Column("formula_type", sa.String(32), nullable=False),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("score_mapping", sa.JSON(), nullable=False),
        sa.Column("applicability_rule", sa.JSON(), nullable=False),
        sa.Column("input_fields", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("active_from", sa.Date(), nullable=False),
        sa.UniqueConstraint("criterion_code", "version", name="uq_assessment_criteria_code_version"),
    )
    op.create_index("ix_assessment_criteria_is_active", "assessment_criteria", ["is_active"])
    op.create_index("ix_assessment_criteria_criterion_code", "assessment_criteria", ["criterion_code"])

    criteria_table = sa.table(
        "assessment_criteria",
        sa.column("id", sa.Uuid()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        sa.column("criterion_code", sa.String),
        sa.column("section_code", sa.String),
        sa.column("section_title", sa.String),
        sa.column("name", sa.Text),
        sa.column("subject_type", sa.String),
        sa.column("period_type", sa.String),
        sa.column("input_type", sa.String),
        sa.column("formula_type", sa.String),
        sa.column("thresholds", sa.JSON),
        sa.column("score_mapping", sa.JSON),
        sa.column("applicability_rule", sa.JSON),
        sa.column("input_fields", sa.JSON),
        sa.column("is_active", sa.Boolean),
        sa.column("display_order", sa.Integer),
        sa.column("version", sa.Integer),
        sa.column("active_from", sa.Date),
    )
    op.bulk_insert(
        criteria_table,
        [
            {
                "id": uuid4(),
                "created_at": now,
                "updated_at": now,
                "criterion_code": item["criterion_code"],
                "section_code": item["section_code"],
                "section_title": item["section_title"],
                "name": item["name"],
                "subject_type": item["subject_type"],
                "period_type": item["period_type"],
                "input_type": item["input_type"],
                "formula_type": item["formula_type"],
                "thresholds": item["thresholds"],
                "score_mapping": item["score_mapping"],
                "applicability_rule": item["applicability_rule"],
                "input_fields": item["input_fields"],
                "is_active": True,
                "display_order": item["display_order"],
                "version": 1,
                "active_from": date(2026, 1, 1),
            }
            for item in CRITERIA
        ],
    )

    op.create_table(
        "assessment_facts",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criterion_id", sa.Uuid(), sa.ForeignKey("assessment_criteria.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(16), nullable=False),
        sa.Column("period_index", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(16), nullable=False),
        sa.Column("department_id", sa.Uuid(), sa.ForeignKey("departments.id", ondelete="RESTRICT")),
        sa.Column("subject_key", sa.String(96), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("not_applicable", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("comment", sa.Text()),
        sa.Column("entered_by_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
        sa.UniqueConstraint(
            "criterion_id",
            "period_year",
            "period_type",
            "period_index",
            "subject_key",
            name="uq_assessment_fact_scope",
        ),
    )
    op.create_index("ix_assessment_facts_criterion_id", "assessment_facts", ["criterion_id"])
    op.create_index("ix_assessment_facts_department_id", "assessment_facts", ["department_id"])

    op.create_table(
        "assessment_results",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(16), nullable=False),
        sa.Column("period_index", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(16), nullable=False),
        sa.Column("department_id", sa.Uuid(), sa.ForeignKey("departments.id", ondelete="RESTRICT")),
        sa.Column("subject_key", sa.String(96), nullable=False),
        sa.Column("criteria_payload", sa.JSON(), nullable=False),
        sa.Column("average_score", sa.Float()),
        sa.Column("verdict", sa.String(32)),
        sa.Column("applicable_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("not_applicable_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("missing_input_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
        sa.UniqueConstraint("period_year", "period_type", "period_index", "subject_key", name="uq_assessment_result_scope"),
    )
    op.create_index("ix_assessment_results_department_id", "assessment_results", ["department_id"])


def downgrade() -> None:
    op.drop_table("assessment_results")
    op.drop_table("assessment_facts")
    op.drop_table("assessment_criteria")
