"""Добавить проверки и нарушения

Revision ID: 43594a0dc7a3
Revises: 20261005_01
Create Date: 2026-10-05 23:03:57.548555

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43594a0dc7a3'
down_revision: str | Sequence[str] | None = '20261005_01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('control_type_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_kind_id', sa.Uuid(), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=False),
    sa.Column('document_number_normalized', sa.String(length=128), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_type_id'], ['control_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_kind_id'], ['inspection_kinds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_type_id', 'document_number_normalized', name='uq_inspection_control_number')
    )
    op.create_index(op.f('ix_inspections_control_type_id'), 'inspections', ['control_type_id'], unique=False)
    op.create_index(op.f('ix_inspections_document_number_normalized'), 'inspections', ['document_number_normalized'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_date'), 'inspections', ['inspection_date'], unique=False)
    op.create_table('inspection_scopes',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_scopes_inspection_id'), 'inspection_scopes', ['inspection_id'], unique=False)
    op.create_table('violations',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_scope_id', sa.Uuid(), nullable=False),
    sa.Column('formulation', sa.Text(), nullable=False),
    sa.Column('violated_requirement', sa.Text(), nullable=False),
    sa.Column('violation_type_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('original_due_date', sa.Date(), nullable=True),
    sa.Column('due_date_basis', sa.String(length=255), nullable=True),
    sa.Column('due_date_source_text', sa.Text(), nullable=True),
    sa.Column('document_received_date', sa.Date(), nullable=True),
    sa.Column('elimination_date', sa.Date(), nullable=True),
    sa.Column('eliminated_during_inspection', sa.Boolean(), nullable=False),
    sa.Column('eliminated_late', sa.Boolean(), nullable=False),
    sa.Column('days_overdue_at_elimination', sa.Integer(), nullable=True),
    sa.Column('annulled', sa.Boolean(), nullable=False),
    sa.Column('annulled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('annulled_by_id', sa.Uuid(), nullable=True),
    sa.Column('annulment_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annulled_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_scope_id'], ['inspection_scopes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['violation_type_id'], ['violation_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_annulled'), 'violations', ['annulled'], unique=False)
    op.create_index(op.f('ix_violations_due_date'), 'violations', ['due_date'], unique=False)
    op.create_index(op.f('ix_violations_elimination_date'), 'violations', ['elimination_date'], unique=False)
    op.create_index(op.f('ix_violations_inspection_id'), 'violations', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_violations_inspection_scope_id'), 'violations', ['inspection_scope_id'], unique=False)
    op.create_table('deadline_change_requests',
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('requested_due_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_change_requests_violation_id'), 'deadline_change_requests', ['violation_id'], unique=False)
    op.create_table('deadline_changes',
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('old_due_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_changes_violation_id'), 'deadline_changes', ['violation_id'], unique=False)
    op.create_table('repeat_links',
    sa.Column('source_violation_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_violation_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_violation_id', 'candidate_violation_id', name='uq_repeat_link_pair')
    )
    op.create_table('violation_responsible_departments',
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('violation_id', 'department_id', name='uq_violation_responsible_department')
    )
    op.create_table('violation_responsible_persons',
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('violation_id', 'person_id', name='uq_violation_responsible_person')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_responsible_persons')
    op.drop_table('violation_responsible_departments')
    op.drop_table('repeat_links')
    op.drop_index(op.f('ix_deadline_changes_violation_id'), table_name='deadline_changes')
    op.drop_table('deadline_changes')
    op.drop_index(op.f('ix_deadline_change_requests_violation_id'), table_name='deadline_change_requests')
    op.drop_table('deadline_change_requests')
    op.drop_index(op.f('ix_violations_inspection_scope_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_inspection_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_elimination_date'), table_name='violations')
    op.drop_index(op.f('ix_violations_due_date'), table_name='violations')
    op.drop_index(op.f('ix_violations_annulled'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_inspection_scopes_inspection_id'), table_name='inspection_scopes')
    op.drop_table('inspection_scopes')
    op.drop_index(op.f('ix_inspections_inspection_date'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_document_number_normalized'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_control_type_id'), table_name='inspections')
    op.drop_table('inspections')
    # ### end Alembic commands ###
