export type CurrentUser = { id: string; login: string; display_name: string; roles: string[] }
export type ReferenceItem = { id: string; code: string; name: string; is_active: boolean; display_order: number }
export type UserItem = { id: string; login: string; display_name: string; is_active: boolean; roles: string[] }
export type InspectionItem = { id: string; control_type_id: string; has_deadline_control: boolean; inspection_kind_id: string | null; department_id: string | null; object_id: string | null; document_number: string; inspection_date: string; state: 'draft' | 'editing' | 'in_progress'; comment: string | null }
export type ObjectItem = { id: string; code: string; name: string; owner_department_id: string | null; is_active: boolean; display_order: number }
export type PersonItem = { id: string; full_name: string; position: string | null; department_id: string | null; is_active: boolean; display_order: number }
export type ViolationTypeItem = { id: string; code: string; name: string; severity: number; is_active: boolean }
export type MeasureItem = { id: string; violation_id: string; department_id: string; object_id: string; person_id: string; elimination_measure: string; due_date: string | null; original_due_date: string | null; elimination_date: string | null; eliminated_during_inspection: boolean; eliminated_late: boolean; days_overdue_at_elimination: number | null; status: 'eliminated' | 'not_eliminated' | 'overdue' }
export type MeasureInput = { department_id: string; object_id: string; person_id: string; elimination_measure: string; due_date?: string }
export type ViolationItem = { id: string; inspection_id: string; has_deadline_control: boolean; formulation: string; violated_requirement: string; severity: number; document_received_date: string | null; annulled: boolean; status: 'eliminated' | 'not_eliminated' | 'overdue' | null; measures: MeasureItem[]; due_date?: string | null; elimination_date?: string | null }
export type DeadlineControlItem = { measure_id: string; violation_id: string; inspection_id: string; document_number: string; inspection_date: string; control_type_id: string; control_type_code: string; control_type_name: string; department_id: string; department_name: string; object_id: string; object_name: string; person_id: string; person_name: string; person_position: string | null; violation_formulation: string; elimination_measure: string; due_date: string | null; original_due_date: string | null; elimination_date: string | null; eliminated_during_inspection: boolean; eliminated_late: boolean; days_overdue_at_elimination: number | null; status: 'eliminated' | 'not_eliminated' | 'overdue'; days_overdue: number; days_left: number | null; due_soon: boolean }
export type DeadlineControlSummary = { total: number; overdue: number; due_soon: number; not_eliminated: number; eliminated: number; eliminated_late: number }
export type DeadlineTypeSummary = { control_type_id: string; code: string; name: string; total: number; overdue: number; due_soon: number; not_eliminated: number; eliminated: number; eliminated_late: number }
export type DeadlineControlResponse = { summary: DeadlineControlSummary; types: DeadlineTypeSummary[]; items: DeadlineControlItem[] }
export type DeadlineChangeItem = { id: string; violation_measure_id: string; old_due_date: string; new_due_date: string; reason: string; changed_by_id: string; changed_at: string }
export type ImportResponsible = { raw: string; name: string | null; position: string | null; person_id: string | null; person_name: string | null }
export type ImportPreviewRow = { row_number: number; values: Record<string, string>; due_date: string | null; responsible: ImportResponsible | null; errors: string[] }
export type ImportPreview = { file_name: string; headers: string[]; mapping: Record<string, string>; rows: ImportPreviewRow[]; valid_rows: number; invalid_rows: number }
export type AnalyticsSummary = { total: number; eliminated: number; not_eliminated: number; overdue: number; due_soon: number; eliminated_late: number; heavy: number }
export type AnalyticsControlTypeItem = { control_type_id: string; code: string; name: string; total: number; eliminated: number; not_eliminated: number; overdue: number; heavy: number }
export type AnalyticsSeverityItem = { severity: number; total: number }
export type AnalyticsDepartmentItem = { department_id: string; name: string; total: number; eliminated: number; not_eliminated: number; overdue: number; heavy: number }
export type AnalyticsObjectItem = { object_id: string; name: string; total: number; heavy: number }
export type AnalyticsDynamicsPoint = { month: string; total: number; by_control_type: Record<string, number> }
export type AnalyticsViolationTypeItem = { violation_type_id: string; code: string; name: string; severity: number; total: number }
export type AnalyticsResponse = { period_from: string | null; period_to: string | null; summary: AnalyticsSummary; by_control_type: AnalyticsControlTypeItem[]; by_severity: AnalyticsSeverityItem[]; by_department: AnalyticsDepartmentItem[]; by_object: AnalyticsObjectItem[]; dynamics: AnalyticsDynamicsPoint[]; by_violation_type: AnalyticsViolationTypeItem[] }
export type AnalyticsFilterParams = { date_from?: string; date_to?: string; control_type_id?: string; department_id?: string; object_id?: string; severity?: string; status?: string }
export type AssessmentPeriodType = 'quarter' | 'half_year' | 'nine_months' | 'year'
export type AssessmentCriterionItem = { id: string; criterion_code: string; section_code: string; section_title: string; name: string; subject_type: 'department' | 'service'; period_type: AssessmentPeriodType; input_type: 'manual' | 'auto' | 'mixed'; formula_type: string; thresholds: Record<string, unknown>; score_mapping: Record<string, unknown>; applicability_rule: Record<string, unknown>; input_fields: Array<{ key: string; label: string; kind: 'date' | 'bool' | 'number' }>; is_active: boolean; display_order: number; version: number; active_from: string }
export type AssessmentCriterionResult = { criterion_id: string; criterion_code: string; section_code: string; section_title: string; name: string; subject_type: 'department' | 'service'; period_type: AssessmentPeriodType; input_type: 'manual' | 'auto' | 'mixed'; formula_type: string; score: number | null; not_applicable: boolean; missing_input: boolean; fact: string | null; threshold: string | null; reason: string; score_mapping: Record<string, unknown>; input_fields: Array<{ key: string; label: string; kind: 'date' | 'bool' | 'number' }>; fact_values: Record<string, unknown>; fact_not_applicable: boolean; fact_comment: string | null }
export type AssessmentSummary = { applicable_count: number; not_applicable_count: number; missing_input_count: number; average_score: number | null; verdict: string | null }
export type AssessmentComputeResponse = { period_type: AssessmentPeriodType; period_year: number; period_index: number; period_from: string; period_to: string; department_id: string | null; department_name: string | null; subject_type: 'department' | 'service'; summary: AssessmentSummary; criteria: AssessmentCriterionResult[] }
export type AssessmentFactItem = { id: string; criterion_id: string; criterion_code: string | null; period_year: number; period_type: AssessmentPeriodType; period_index: number; subject_type: 'department' | 'service'; department_id: string | null; values: Record<string, unknown>; not_applicable: boolean; comment: string | null; updated_at: string }
export type AssessmentFactSave = { criterion_id: string; period_type: AssessmentPeriodType; period_year: number; period_index: number; department_id: string | null; values: Record<string, unknown>; not_applicable: boolean; comment: string | null }
export type AssessmentResultItem = { id: string; period_year: number; period_type: AssessmentPeriodType; period_index: number; subject_type: 'department' | 'service'; department_id: string | null; department_name: string | null; average_score: number | null; verdict: string | null; applicable_count: number; not_applicable_count: number; missing_input_count: number; created_by_id: string; created_at: string; updated_at: string }
export type AssessmentResultDetail = AssessmentResultItem & { criteria_payload: AssessmentCriterionResult[] }

export class ApiError extends Error { constructor(message: string, public status: number) { super(message) } }

let unauthorizedHandler: (() => void) | null = null
export function setUnauthorizedHandler(handler: (() => void) | null) { unauthorizedHandler = handler }

async function request<T>(path: string, token: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`/api/v1${path}`, { ...options, headers: { Accept: 'application/json', ...(options?.body && !(options.body instanceof FormData) ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options?.headers } })
  if (!response.ok) { const body = await response.json().catch(() => null) as { detail?: string } | null; if (response.status === 401 && token) unauthorizedHandler?.(); throw new ApiError(body?.detail ?? 'Не удалось выполнить запрос', response.status) }
  return response.json() as Promise<T>
}

export async function login(loginValue: string, password: string): Promise<string> { return (await request<{ access_token: string }>('/auth/login', '', { method: 'POST', body: JSON.stringify({ login: loginValue, password }) })).access_token }

export const api = {
  me: (token: string) => request<CurrentUser>('/auth/me', token),
  references: (token: string, resource: string) => request<ReferenceItem[]>(`/references/${resource}?include_inactive=true`, token),
  users: (token: string) => request<UserItem[]>('/users', token),
  inspections: (token: string) => request<InspectionItem[]>('/inspections', token),
  createInspection: (token: string, payload: { control_type_id: string; inspection_kind_id?: string; department_id?: string; object_id?: string; document_number: string; inspection_date: string; comment?: string }) => request<InspectionItem>('/inspections', token, { method: 'POST', body: JSON.stringify(payload) }),
  updateInspection: (token: string, inspectionId: string, payload: { inspection_kind_id?: string | null; department_id?: string | null; object_id?: string | null; document_number: string; inspection_date: string; comment?: string }) => request<InspectionItem>(`/inspections/${inspectionId}`, token, { method: 'PATCH', body: JSON.stringify(payload) }),
  objects: (token: string) => request<ObjectItem[]>('/references/objects/items?include_inactive=true', token),
  persons: (token: string) => request<PersonItem[]>('/references/persons/items?include_inactive=true', token),
  violationTypes: (token: string) => request<ViolationTypeItem[]>('/references/violation-types/items', token),
  createViolation: (token: string, inspectionId: string, payload: { formulation: string; violated_requirement: string; violation_type_id: string; document_received_date?: string; measures?: MeasureInput[]; inspection_scope_id?: string; due_date?: string; elimination_measure?: string }) => request<ViolationItem>(`/inspections/${inspectionId}/violations`, token, { method: 'POST', body: JSON.stringify(payload) }),
  previewImport: (token: string, inspectionId: string, file: File, mapping: Record<string, string>, headerRow: number) => { const body = new FormData(); body.append('file', file); body.append('mapping', JSON.stringify(mapping)); body.append('header_row', String(headerRow)); return request<ImportPreview>(`/inspections/${inspectionId}/imports/preview`, token, { method: 'POST', body }) },
  confirmImport: (token: string, inspectionId: string, payload: { rows: Array<{ formulation: string; violated_requirement: string; violation_type_id: string; measures: MeasureInput[] }> }) => request<{ created_violations: number; created_measures: number }>(`/inspections/${inspectionId}/imports/confirm`, token, { method: 'POST', body: JSON.stringify(payload) }),
  violations: (token: string) => request<ViolationItem[]>('/violations', token),
  eliminateMeasure: (token: string, measureId: string, payload: { elimination_date: string; eliminated_during_inspection?: boolean }) => request<MeasureItem>(`/measures/${measureId}/elimination`, token, { method: 'POST', body: JSON.stringify(payload) }),
  changeMeasureDeadline: (token: string, measureId: string, payload: { new_due_date: string; reason: string }) => request<DeadlineChangeItem>(`/measures/${measureId}/deadline-changes`, token, { method: 'POST', body: JSON.stringify(payload) }),
  deadlineChanges: (token: string, measureId: string) => request<DeadlineChangeItem[]>(`/measures/${measureId}/deadline-changes`, token),
  deadlineControl: (token: string, params: { status?: string; department_id?: string; person_id?: string }) => { const query = new URLSearchParams(); if (params.status) query.set('status', params.status); if (params.department_id) query.set('department_id', params.department_id); if (params.person_id) query.set('person_id', params.person_id); const suffix = query.toString(); return request<DeadlineControlResponse>(`/deadline-control${suffix ? `?${suffix}` : ''}`, token) },
  analytics: (token: string, params: AnalyticsFilterParams) => { const query = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value) query.set(key, value); const suffix = query.toString(); return request<AnalyticsResponse>(`/analytics/summary${suffix ? `?${suffix}` : ''}`, token) },
  assessmentCriteria: (token: string) => request<AssessmentCriterionItem[]>('/assessment/criteria', token),
  assessmentCompute: (token: string, payload: { period_type: AssessmentPeriodType; period_year: number; period_index: number; department_id?: string | null }) => request<AssessmentComputeResponse>('/assessment/compute', token, { method: 'POST', body: JSON.stringify(payload) }),
  assessmentFacts: (token: string, params: { period_type: AssessmentPeriodType; period_year: number; period_index: number; department_id?: string | null }) => { const query = new URLSearchParams({ period_type: params.period_type, period_year: String(params.period_year), period_index: String(params.period_index) }); if (params.department_id) query.set('department_id', params.department_id); return request<AssessmentFactItem[]>(`/assessment/facts?${query.toString()}`, token) },
  assessmentSaveFact: (token: string, payload: AssessmentFactSave) => request<AssessmentFactItem>('/assessment/facts', token, { method: 'POST', body: JSON.stringify(payload) }),
  assessmentResults: (token: string, params: { period_type?: AssessmentPeriodType; period_year?: number; department_id?: string } = {}) => { const query = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value) query.set(key, String(value)); const suffix = query.toString(); return request<AssessmentResultItem[]>(`/assessment/results${suffix ? `?${suffix}` : ''}`, token) },
  assessmentResultDetail: (token: string, resultId: string) => request<AssessmentResultDetail>(`/assessment/results/${resultId}`, token),
  assessmentSaveResult: (token: string, payload: { period_type: AssessmentPeriodType; period_year: number; period_index: number; department_id?: string | null }) => request<AssessmentResultItem>('/assessment/results', token, { method: 'POST', body: JSON.stringify(payload) }),
}
